# Generated by Django 5.0.4 on 2024-05-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_rentals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
