# Generated by Django 5.0.4 on 2024-05-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_rentals", "0002_car_description_car_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="image_url",
        ),
        migrations.AddField(
            model_name="car",
            name="image_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
